//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConatactDetail
    {
        public string City { get; set; }
        public string Location1 { get; set; }
        public string ContactNo1 { get; set; }
        public string Location2 { get; set; }
        public string ConatactNo2 { get; set; }
        public string Location3 { get; set; }
        public string ConatactNo3 { get; set; }
    }
}
