//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignment
    {
        public int CId { get; set; }
        public string Consignment_Type { get; set; }
        public string Reciver_Name { get; set; }
        public string Reciver_Address { get; set; }
        public string Reciver_MobileNO { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PickupType { get; set; }
    
        public virtual User User { get; set; }
    }
}
