//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogisticManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int Bid { get; set; }
        public Nullable<System.DateTime> Consignment_Procurement { get; set; }
        public Nullable<System.DateTime> Consignment_Ready { get; set; }
        public Nullable<System.DateTime> In_Transit { get; set; }
        public Nullable<System.DateTime> Delivered { get; set; }
    }
}
